CREATE TABLE authors (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE books (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(255) NOT NULL,
    author_id BIGINT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES authors (id)
);

-- B-treeインデックス: author_idでの検索・JOINを高速化する
-- H2のCREATE INDEXはデフォルトでB-treeを使用する
CREATE INDEX idx_books_author_id ON books (author_id);
